version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: app
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    networks:
      - envoymesh

  envoy:
    build:
      context: .
      dockerfile: Dockerfile.envoy
    container_name: envoy
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./service_descriptor.pb:/data/service_descriptor.pb
    depends_on:
      - app
    networks:
      - envoymesh

networks:
  envoymesh:
    driver: bridge
